[package]
name = "suroi_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"
phf = { version = "0.11", features = ["macros"] }
